import { PhukienProvider } from "./context/PhukienContext";

import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Bọc toàn bộ ứng dụng trong Provider */}
        <PhukienProvider>{children}</PhukienProvider>
      </body>
    </html>
  );
}
